[package]
name = "batrun-cli"
version = "2.0.0-alpha"
edition = "2024"

[[bin]]
name = "batrun"
path = "src/main.rs"

[dependencies]
batrun = { path = "..", features = ["clap"] }
clap = { version = "4.5", features = ["derive"] }
